# 参考
# https://qiita.com/katsuomi/items/d1e6625ae9a5b663e11f
version: '3.8'
services:
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd react-sample && npm install && yarn start"
    ports:
      - "3000:3000"
  api:
    build:
        context: ./backend
    volumes:
        - ./backend/src:/go/src
    ports:
        - 8080:8080
    tty: true
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: hogehoge-api
      POSTGRES_PASSWORD: hogehoge-api
      POSTGRES_DB: hogehoge-api
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.21.6
    ports:
      - 8000:80
    environment:
      - TZ=Asia/tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
